name: TV Monitor

on:
  schedule:
    - cron: '0 16-23 * * *'
    - cron: '0 0-3 * * *'

    # PST (UTC-8): runs 17:00–04:00 UTC → 9am–8pm LA
    - cron: '0 17-23 * * *'
    - cron: '0 0-4 * * *'
  workflow_dispatch: # allow manual run

jobs:
  check-tvs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore seen.json from cache
        uses: actions/cache@v4
        with:
          path: seen.json
          key: seen-json-cache

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.mjs
        env:
          BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}

      - name: Save seen.json to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: seen.json
          key: seen-json-cache
