name: Run Telegram Bot

on:
  schedule:
    - cron: '0 * * * *' # every 30 minutes
  workflow_dispatch: # allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Telegram bot
        run: node index.js

